"""auto update

Revision ID: a79d4476e8e9
Revises: 
Create Date: 2026-03-20 03:04:57.210063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a79d4476e8e9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dossiers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('applicant_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('commune', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('cadastral_section', sa.String(), nullable=True),
    sa.Column('parcel', sa.String(), nullable=True),
    sa.Column('land_area', sa.String(), nullable=True),
    sa.Column('land_status', sa.String(), nullable=True),
    sa.Column('environment', sa.String(), nullable=True),
    sa.Column('topography', sa.String(), nullable=True),
    sa.Column('vegetation', sa.String(), nullable=True),
    sa.Column('access', sa.String(), nullable=True),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('project_type', sa.String(), nullable=True),
    sa.Column('lodge_model', sa.String(), nullable=True),
    sa.Column('unit_count', sa.String(), nullable=True),
    sa.Column('finish_level', sa.String(), nullable=True),
    sa.Column('architect_description', sa.String(), nullable=True),
    sa.Column('file_key', sa.String(), nullable=True),
    sa.Column('layout_disposition', sa.String(), nullable=True),
    sa.Column('unit_distance', sa.String(), nullable=True),
    sa.Column('vegetation_preservation', sa.String(), nullable=True),
    sa.Column('parking', sa.String(), nullable=True),
    sa.Column('road_access', sa.String(), nullable=True),
    sa.Column('connections', sa.String(), nullable=True),
    sa.Column('project_objective', sa.String(), nullable=True),
    sa.Column('integration_level', sa.String(), nullable=True),
    sa.Column('environmental_commitment', sa.String(), nullable=True),
    sa.Column('maximize_acceptance', sa.Boolean(), nullable=True),
    sa.Column('generated_prompt', sa.String(), nullable=True),
    sa.Column('payment_status', sa.String(), nullable=True),
    sa.Column('stripe_session_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dossiers_id'), 'dossiers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dossiers_id'), table_name='dossiers')
    op.drop_table('dossiers')
    # ### end Alembic commands ###